<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DT1</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>3af8c968-bf3b-4066-9685-08adb8e48ee1</testSuiteGuid>
   <testCaseLink>
      <guid>3aaadc8c-d0ab-489b-bdaa-faf71c4d2173</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DT1</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>c3486f2e-25c8-4f64-a6aa-5e053b1eb489</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DT1</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>c3486f2e-25c8-4f64-a6aa-5e053b1eb489</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username1</value>
         <variableId>c85fd424-1f08-4e25-b745-ee0b8135ac6c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c3486f2e-25c8-4f64-a6aa-5e053b1eb489</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password1</value>
         <variableId>bad8ade7-97ca-456d-ba10-8fc0dfd3a730</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
