<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h5_Compare Packages</name>
   <tag></tag>
   <elementGuidId>8bbd6fe1-127e-465f-a01b-aaf066b4b113</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navbarSupportedContent']/ul/li/div/div/div/div/ul/li/div/ul/div/a/h5</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h5.text-center</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Compare Packages' or . = 'Compare Packages')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>4f425f9f-601c-45c2-ad02-73735a5bc63a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-center</value>
      <webElementGuid>560d6b0d-9f6f-46c1-acf4-5220f37bd509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Compare Packages</value>
      <webElementGuid>dd8cb451-03f7-4abc-9935-d66bdc7e1ae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarSupportedContent&quot;)/ul[@class=&quot;navbar-nav me-auto mb-2 mb-lg-0 web-menu&quot;]/li[@class=&quot;nav-item&quot;]/div[@class=&quot;secondary&quot;]/div[@class=&quot;col-md-12 col-lg-12&quot;]/div[@class=&quot;sub-menu&quot;]/div[@class=&quot;secondary-menu&quot;]/ul[1]/li[@class=&quot;sub-menu-title menu-title-row pt-2 pb-2&quot;]/div[@class=&quot;menu-title-row-view-platform&quot;]/ul[@class=&quot;extra-menu-section&quot;]/div[@class=&quot;compare-menu&quot;]/a[1]/h5[@class=&quot;text-center&quot;]</value>
      <webElementGuid>7b551aa9-7842-4172-ab5e-af8b4c76313f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarSupportedContent']/ul/li/div/div/div/div/ul/li/div/ul/div/a/h5</value>
      <webElementGuid>9f9488a7-0f55-4641-bf3b-c39854bed178</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADVANCED'])[1]/following::h5[1]</value>
      <webElementGuid>09625be9-bcc8-4b64-af45-516a98f6aa47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='STARTER (Open-Source)'])[1]/following::h5[1]</value>
      <webElementGuid>4bb5fe18-f8b4-4609-943c-2cbebaf39ab4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recruitment (ATS)'])[1]/preceding::h5[1]</value>
      <webElementGuid>1977db88-113b-47b9-8370-ba72f9e08399</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Compare Packages']/parent::*</value>
      <webElementGuid>bc047a3a-e5b1-41d0-bb1d-e0109b383318</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h5</value>
      <webElementGuid>a50914f6-79e8-4fc7-81a1-714fe0c299db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h5[(text() = 'Compare Packages' or . = 'Compare Packages')]</value>
      <webElementGuid>8efb788a-6d26-4dfe-a10d-cf5b2a1781ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
